name: Publish Python Package to PyPI

on:
  release:
    types: [created] # Triggered when a new GitHub Release is created

jobs:
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout the repository
      # id-token: write # Needed for trusted publishing (optional, more advanced)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Or your desired Python version for building

    - name: Install dependencies for build
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* -u __token__ -p $PYPI_API_TOKEN
